server:
  port: 8080

spring:
  profiles:
    include: datasource

  output:
    ansi:
      enabled: detect # 콘솔 로그 색상 출력

api:
  path:
    default: /api/v1
#  jwt:
#    secret: ${JWT_SECRET}
#    expire: ${JWT_EXPIRE:600} # seconds

# aws s3 file server
aws-s3:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket-name: ${AWS_BUCKET_NAME}